name: Get actual version from package.json without checkout
author: Luis Andino
description: |
  This will retrieve the actual package.json version
outputs:
  actualVersion:
    description: The version obtained from the package.json
    value: ${{ steps.version_getter.outputs.actualVersion }}
runs:
  using: composite
  steps:
    - name: Getting the version
      id: version_getter
      shell: bash
      run: |
        VERSION=$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo "Your version is:" $VERSION
        echo "::set-output name=actualVersion::$(echo $VERSION)"
